### ISSUE TITLE
使用docker镜像，在k8s中部署，启动时出现报错

### ISSUE THREAD

**Issue by aosolao** [eryajf/go-ldap-admin#241]
#### 您使用的版本？ | Your usage version?

docker 镜像版本：eryajf/go-ldap-admin-server:2023-07-20_12-53

在容器启动时出现了下面的错误日志，服务无法启动：
```
[INFO  wait] --------------------------------------------------------
[INFO  wait]  docker-compose-wait 2.9.0
[INFO  wait] ---------------------------
[DEBUG wait] Starting with configuration:
[DEBUG wait]  - Hosts to be waiting for: []
[DEBUG wait]  - Paths to be waiting for: []
[DEBUG wait]  - Timeout before failure: 30 seconds 
[DEBUG wait]  - TCP connection timeout before retry: 5 seconds 
[DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
[DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
[DEBUG wait]  - Sleeping time between retries: 1 seconds
[DEBUG wait] --------------------------------------------------------
[INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
[INFO  wait] --------------------------------------------------------
2023-08-04 15:53:53	INFO	common/logger.go:110	github.com/eryajf/go-ldap-admin/public/common.InitLogger	初始化zap日志完成!
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe18de1]

goroutine 1 [running]:
github.com/eryajf/go-ldap-admin/public/common.InitDB()
	/app/public/common/database.go:19 +0x21
main.main()
	/app/main.go:29 +0x4f
```

**Comment by eryajf** [comment]
您好 @aosolao👋，我已收到您的反馈，我将安排时间考虑您提交的信息并进行回复。-- 这条信息是由自动回复的机器人发出的。

Hello @aosolao. I have received your feedback, and I will arrange time to consider the information you submitted and reply. -- This message is sent by an automatic reply robot.

**Comment by eryajf** [comment]
应该是配置文件的问题，没有正常连到数据库

**Comment by aosolao** [comment]
是的配置文件里漏了下面这部分
```
database:
  # 数据库类型 mysql sqlite3
  driver: mysql
```
已解决谢谢

**Comment by yunkaiOr2** [comment]
@aosolao 可以贴一下你的apply文件吗，我也想部署到k8s环境中，目前报错，启动不起来。

**Comment by eryajf** [comment]
> @aosolao 可以贴一下你的apply文件吗，我也想部署到k8s环境中，目前报错，启动不起来。

你也可以先贴一下你的操作上下文
